# Generated by Django 2.2.4 on 2019-08-24 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Roast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roast', models.CharField(max_length=280)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('downvotes', models.ManyToManyField(related_name='roast_downvotes', to='ghostpost.AnonUser')),
                ('upvotes', models.ManyToManyField(related_name='roast_upvotes', to='ghostpost.AnonUser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghostpost.AnonUser')),
            ],
        ),
        migrations.CreateModel(
            name='Boast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boast', models.CharField(max_length=280)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('downvotes', models.ManyToManyField(related_name='boast_downvotes', to='ghostpost.AnonUser')),
                ('upvotes', models.ManyToManyField(related_name='boast_upvotes', to='ghostpost.AnonUser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghostpost.AnonUser')),
            ],
        ),
    ]
