# Generated by Django 2.2.4 on 2019-08-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0002_auto_20190822_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='boast',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='boast',
            name='updated_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='roast',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='roast',
            name='updated_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='boast',
            name='boast',
        ),
        migrations.AddField(
            model_name='boast',
            name='boast',
            field=models.ManyToManyField(max_length=280, related_name='boasts', to='ghostpost.Author'),
        ),
        migrations.RemoveField(
            model_name='roast',
            name='roast',
        ),
        migrations.AddField(
            model_name='roast',
            name='roast',
            field=models.ManyToManyField(max_length=280, related_name='roasts', to='ghostpost.Author'),
        ),
    ]
